### ISSUE TITLE
images published to hub.docker.com should be tagged

### ISSUE THREAD

**Issue by jpbochi** [airdock-io/docker-fake-sqs#2]
I've been using `airdock/fake-sqs` for my SQS integration tests, and recently the tests crashed because we caught up a breaking change to the published image. Since the only image at hub.docker.com is `latest`, there was no easy way fix to an older version. Can you please tag your images?

In https://github.com/jpbochi/local-dynamodb, for example, I scripted a way to ensure that I publish images that match the version of the [DynamoDBLocal](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) build by AWS. This way, I ensure that people can choose to upgrade at their leisure.

**Comment by geronimo-iia** [comment]
Hello, sorry for that,
When I was fixing a build issue, I forget to tag previous images...
I'll do it asap

Jerome

**Comment by geronimo-iia** [comment]
it's coming soon: https://github.com/airdock-io/docker-fake-sqs/pull/3

**Comment by jpbochi** [comment]
cool! thanks
